"""Add daily attendance records and exceptions

Revision ID: 2fc5b4d5d552
Revises: 001
Create Date: 2025-08-01 00:07:53.138446

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2fc5b4d5d552"
down_revision: Union[str, None] = "20250804_2300_001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attendance_exceptions",
        sa.Column(
            "member_id",
            sa.Integer(),
            nullable=False,
            comment="Member ID who made the request",
        ),
        sa.Column(
            "exception_type",
            sa.String(length=50),
            nullable=False,
            comment="Type of exception (迟到/早退/忘记打卡/请假等)",
        ),
        sa.Column(
            "exception_date", sa.Date(), nullable=False, comment="Date of the exception"
        ),
        sa.Column(
            "reason", sa.Text(), nullable=False, comment="Reason for the exception"
        ),
        sa.Column(
            "supporting_documents",
            sa.Text(),
            nullable=True,
            comment="Supporting documents or evidence",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "APPROVED", "REJECTED", name="attendanceexceptionstatus"
            ),
            nullable=False,
            comment="Processing status",
        ),
        sa.Column(
            "applied_at",
            sa.DateTime(),
            nullable=False,
            comment="When the request was submitted",
        ),
        sa.Column(
            "reviewer_id",
            sa.Integer(),
            nullable=True,
            comment="ID of the reviewer (admin)",
        ),
        sa.Column(
            "reviewer_comments",
            sa.Text(),
            nullable=True,
            comment="Comments from the reviewer",
        ),
        sa.Column(
            "reviewed_at",
            sa.DateTime(),
            nullable=True,
            comment="When the request was reviewed",
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Primary key",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Record creation timestamp",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Record last update timestamp",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_exception_member_date",
        "attendance_exceptions",
        ["member_id", "exception_date"],
        unique=False,
    )
    op.create_index(
        "idx_exception_status_date",
        "attendance_exceptions",
        ["status", "applied_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_exceptions_exception_date"),
        "attendance_exceptions",
        ["exception_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_exceptions_id"),
        "attendance_exceptions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_exceptions_member_id"),
        "attendance_exceptions",
        ["member_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_exceptions_status"),
        "attendance_exceptions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "monthly_attendance_summaries",
        sa.Column("member_id", sa.Integer(), nullable=False, comment="Member ID"),
        sa.Column("year", sa.Integer(), nullable=False, comment="Year"),
        sa.Column("month", sa.Integer(), nullable=False, comment="Month (1-12)"),
        sa.Column(
            "repair_task_hours",
            sa.Float(),
            nullable=True,
            comment="Hours from repair tasks",
        ),
        sa.Column(
            "monitoring_task_hours",
            sa.Float(),
            nullable=True,
            comment="Hours from monitoring tasks",
        ),
        sa.Column(
            "assistance_task_hours",
            sa.Float(),
            nullable=True,
            comment="Hours from assistance tasks",
        ),
        sa.Column(
            "overtime_hours", sa.Float(), nullable=True, comment="Overtime hours"
        ),
        sa.Column(
            "bonus_hours",
            sa.Float(),
            nullable=True,
            comment="Bonus hours (rush tasks, positive reviews)",
        ),
        sa.Column(
            "penalty_hours",
            sa.Float(),
            nullable=True,
            comment="Penalty hours (late response, negative reviews)",
        ),
        sa.Column(
            "total_work_hours",
            sa.Float(),
            nullable=True,
            comment="Total calculated work hours",
        ),
        sa.Column(
            "total_attendance_hours",
            sa.Float(),
            nullable=True,
            comment="Total hours from attendance records",
        ),
        sa.Column(
            "total_work_days",
            sa.Integer(),
            nullable=True,
            comment="Total work days in the month",
        ),
        sa.Column(
            "attended_days",
            sa.Integer(),
            nullable=True,
            comment="Days with attendance records",
        ),
        sa.Column(
            "late_days", sa.Integer(), nullable=True, comment="Days with late check-in"
        ),
        sa.Column(
            "early_checkout_days",
            sa.Integer(),
            nullable=True,
            comment="Days with early checkout",
        ),
        sa.Column(
            "task_completion_count",
            sa.Integer(),
            nullable=True,
            comment="Number of completed tasks",
        ),
        sa.Column(
            "average_task_rating",
            sa.Float(),
            nullable=True,
            comment="Average rating for completed tasks",
        ),
        sa.Column(
            "summary_notes", sa.Text(), nullable=True, comment="Monthly summary notes"
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Primary key",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Record creation timestamp",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Record last update timestamp",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "member_id", "year", "month", name="uq_attendance_summary_member_month"
        ),
    )
    op.create_index(
        "idx_summary_member_year",
        "monthly_attendance_summaries",
        ["member_id", "year"],
        unique=False,
    )
    op.create_index(
        "idx_summary_year_month",
        "monthly_attendance_summaries",
        ["year", "month"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monthly_attendance_summaries_id"),
        "monthly_attendance_summaries",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monthly_attendance_summaries_member_id"),
        "monthly_attendance_summaries",
        ["member_id"],
        unique=False,
    )
    # 安全删除索引 - 先检查是否存在
    try:
        op.drop_index(
            op.f("ix_attendance_configurations_config_key"),
            table_name="attendance_configurations",
        )
    except Exception:
        # 索引不存在，忽略错误
        pass
    
    try:
        op.drop_index(
            op.f("ix_attendance_configurations_id"), table_name="attendance_configurations"
        )
    except Exception:
        # 索引不存在，忽略错误
        pass
    op.drop_table("attendance_configurations")
    op.alter_column(
        "assistance_tasks",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING",
            "IN_PROGRESS",
            "COMPLETED",
            "CANCELLED",
            "ON_HOLD",
            name="taskstatus",
        ),
        server_default=None,
        existing_comment="Task status",
        existing_nullable=False,
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "attendance_date", sa.Date(), nullable=False, comment="Attendance date"
        ),
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "checkin_time", sa.DateTime(), nullable=True, comment="Check-in time"
        ),
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "checkout_time", sa.DateTime(), nullable=True, comment="Check-out time"
        ),
    )
    op.add_column(
        "attendance_records",
        sa.Column("work_hours", sa.Float(), nullable=True, comment="Total work hours"),
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "status", sa.String(length=20), nullable=True, comment="Attendance status"
        ),
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "location",
            sa.String(length=200),
            nullable=True,
            comment="Check-in/out location",
        ),
    )
    op.add_column(
        "attendance_records",
        sa.Column("notes", sa.Text(), nullable=True, comment="Attendance notes"),
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "is_late_checkin",
            sa.Boolean(),
            nullable=True,
            comment="Whether check-in was late",
        ),
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "late_checkin_minutes",
            sa.Integer(),
            nullable=True,
            comment="Minutes late for check-in",
        ),
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "is_early_checkout",
            sa.Boolean(),
            nullable=True,
            comment="Whether checkout was early",
        ),
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "early_checkout_minutes",
            sa.Integer(),
            nullable=True,
            comment="Minutes early for checkout",
        ),
    )
    op.drop_index(op.f("idx_attendance_member_month"), table_name="attendance_records")
    op.drop_index(op.f("idx_attendance_month"), table_name="attendance_records")
    op.drop_constraint(
        op.f("uq_attendance_member_month"), "attendance_records", type_="unique"
    )
    op.create_index(
        "idx_attendance_date_member",
        "attendance_records",
        ["attendance_date", "member_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_records_attendance_date"),
        "attendance_records",
        ["attendance_date"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_attendance_member_date",
        "attendance_records",
        ["member_id", "attendance_date"],
    )
    op.drop_table_comment(
        "attendance_records",
        existing_comment="Monthly attendance records table",
        schema=None,
    )
    op.drop_column("attendance_records", "repair_task_hours")
    op.drop_column("attendance_records", "remaining_hours")
    op.drop_column("attendance_records", "calculation_date")
    op.drop_column("attendance_records", "month")
    op.drop_column("attendance_records", "is_final")
    op.drop_column("attendance_records", "assistance_hours")
    op.drop_column("attendance_records", "carried_hours")
    op.drop_column("attendance_records", "monitoring_hours")
    op.drop_column("attendance_records", "details")
    op.drop_column("attendance_records", "total_hours")
    op.alter_column(
        "members",
        "role",
        existing_type=postgresql.ENUM(
            "ADMIN", "GROUP_LEADER", "MEMBER", "GUEST", name="userrole"
        ),
        server_default=None,
        existing_comment="User role",
        existing_nullable=False,
    )
    op.alter_column(
        "members",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_comment="Whether the member is active",
        existing_nullable=False,
    )
    op.alter_column(
        "members",
        "is_verified",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_comment="Whether the member email is verified",
        existing_nullable=False,
    )
    op.alter_column(
        "members",
        "last_login",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Last login timestamp",
        existing_nullable=True,
    )
    op.alter_column(
        "members",
        "login_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_comment="Total login count",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_members_student_id"), table_name="members")
    op.create_index(
        op.f("ix_members_student_id"), "members", ["student_id"], unique=True
    )
    op.alter_column(
        "monitoring_tasks",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING",
            "IN_PROGRESS",
            "COMPLETED",
            "CANCELLED",
            "ON_HOLD",
            name="taskstatus",
        ),
        server_default=None,
        existing_comment="Task status",
        existing_nullable=False,
    )
    op.alter_column(
        "repair_tasks",
        "category",
        existing_type=postgresql.ENUM(
            "NETWORK_REPAIR",
            "HARDWARE_REPAIR",
            "SOFTWARE_SUPPORT",
            "MONITORING",
            "ASSISTANCE",
            "OTHER",
            name="taskcategory",
        ),
        server_default=None,
        existing_comment="Task category",
        existing_nullable=False,
    )
    op.alter_column(
        "repair_tasks",
        "priority",
        existing_type=postgresql.ENUM(
            "LOW", "MEDIUM", "HIGH", "URGENT", name="taskpriority"
        ),
        server_default=None,
        existing_comment="Task priority",
        existing_nullable=False,
    )
    op.alter_column(
        "repair_tasks",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING",
            "IN_PROGRESS",
            "COMPLETED",
            "CANCELLED",
            "ON_HOLD",
            name="taskstatus",
        ),
        server_default=None,
        existing_comment="Task status",
        existing_nullable=False,
    )
    op.alter_column(
        "repair_tasks",
        "task_type",
        existing_type=postgresql.ENUM("ONLINE", "OFFLINE", name="tasktype"),
        server_default=None,
        existing_comment="Task type (online/offline)",
        existing_nullable=False,
    )
    op.alter_column(
        "repair_tasks",
        "work_minutes",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_comment="Calculated work minutes",
        existing_nullable=False,
    )
    op.alter_column(
        "repair_tasks",
        "base_work_minutes",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_comment="Base work minutes before modifiers",
        existing_nullable=False,
    )
    op.alter_column(
        "repair_tasks",
        "is_matched",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_comment="Whether task was matched during import",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_repair_tasks_task_id"), table_name="repair_tasks")
    op.create_index(
        op.f("ix_repair_tasks_task_id"), "repair_tasks", ["task_id"], unique=True
    )
    op.create_index(
        op.f("ix_repair_tasks_report_time"),
        "repair_tasks",
        ["report_time"],
        unique=False,
    )
    op.alter_column(
        "task_tags",
        "work_minutes_modifier",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_comment="Work minutes modifier (+/- minutes)",
        existing_nullable=False,
    )
    op.alter_column(
        "task_tags",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_comment="Whether the tag is active",
        existing_nullable=False,
    )
    op.drop_constraint(op.f("uq_task_tags_name"), "task_tags", type_="unique")
    op.drop_index(op.f("ix_task_tags_name"), table_name="task_tags")
    op.create_index(op.f("ix_task_tags_name"), "task_tags", ["name"], unique=True)
    op.drop_table_comment(
        "task_tags",
        existing_comment="Task tags for categorizing and calculating work hours",
        schema=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        "task_tags",
        "Task tags for categorizing and calculating work hours",
        existing_comment=None,
        schema=None,
    )
    op.drop_index(op.f("ix_task_tags_name"), table_name="task_tags")
    op.create_index(op.f("ix_task_tags_name"), "task_tags", ["name"], unique=False)
    op.create_unique_constraint(
        op.f("uq_task_tags_name"),
        "task_tags",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "task_tags",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_comment="Whether the tag is active",
        existing_nullable=False,
    )
    op.alter_column(
        "task_tags",
        "work_minutes_modifier",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_comment="Work minutes modifier (+/- minutes)",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_repair_tasks_report_time"), table_name="repair_tasks")
    op.drop_index(op.f("ix_repair_tasks_task_id"), table_name="repair_tasks")
    op.create_index(
        op.f("ix_repair_tasks_task_id"), "repair_tasks", ["task_id"], unique=False
    )
    op.alter_column(
        "repair_tasks",
        "is_matched",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_comment="Whether task was matched during import",
        existing_nullable=False,
    )
    op.alter_column(
        "repair_tasks",
        "base_work_minutes",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_comment="Base work minutes before modifiers",
        existing_nullable=False,
    )
    op.alter_column(
        "repair_tasks",
        "work_minutes",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_comment="Calculated work minutes",
        existing_nullable=False,
    )
    op.alter_column(
        "repair_tasks",
        "task_type",
        existing_type=postgresql.ENUM("ONLINE", "OFFLINE", name="tasktype"),
        server_default=sa.text("'ONLINE'::tasktype"),
        existing_comment="Task type (online/offline)",
        existing_nullable=False,
    )
    op.alter_column(
        "repair_tasks",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING",
            "IN_PROGRESS",
            "COMPLETED",
            "CANCELLED",
            "ON_HOLD",
            name="taskstatus",
        ),
        server_default=sa.text("'PENDING'::taskstatus"),
        existing_comment="Task status",
        existing_nullable=False,
    )
    op.alter_column(
        "repair_tasks",
        "priority",
        existing_type=postgresql.ENUM(
            "LOW", "MEDIUM", "HIGH", "URGENT", name="taskpriority"
        ),
        server_default=sa.text("'MEDIUM'::taskpriority"),
        existing_comment="Task priority",
        existing_nullable=False,
    )
    op.alter_column(
        "repair_tasks",
        "category",
        existing_type=postgresql.ENUM(
            "NETWORK_REPAIR",
            "HARDWARE_REPAIR",
            "SOFTWARE_SUPPORT",
            "MONITORING",
            "ASSISTANCE",
            "OTHER",
            name="taskcategory",
        ),
        server_default=sa.text("'NETWORK_REPAIR'::taskcategory"),
        existing_comment="Task category",
        existing_nullable=False,
    )
    op.alter_column(
        "monitoring_tasks",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING",
            "IN_PROGRESS",
            "COMPLETED",
            "CANCELLED",
            "ON_HOLD",
            name="taskstatus",
        ),
        server_default=sa.text("'COMPLETED'::taskstatus"),
        existing_comment="Task status",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_members_student_id"), table_name="members")
    op.create_index(
        op.f("ix_members_student_id"), "members", ["student_id"], unique=False
    )
    op.alter_column(
        "members",
        "login_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_comment="Total login count",
        existing_nullable=False,
    )
    op.alter_column(
        "members",
        "last_login",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_comment="Last login timestamp",
        existing_nullable=True,
    )
    op.alter_column(
        "members",
        "is_verified",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_comment="Whether the member email is verified",
        existing_nullable=False,
    )
    op.alter_column(
        "members",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_comment="Whether the member is active",
        existing_nullable=False,
    )
    op.alter_column(
        "members",
        "role",
        existing_type=postgresql.ENUM(
            "ADMIN", "GROUP_LEADER", "MEMBER", "GUEST", name="userrole"
        ),
        server_default=sa.text("'MEMBER'::userrole"),
        existing_comment="User role",
        existing_nullable=False,
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "total_hours",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0.0"),
            autoincrement=False,
            nullable=False,
            comment="Total work hours (all categories + carried)",
        ),
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "details",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="Detailed calculation breakdown (JSON format)",
        ),
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "monitoring_hours",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0.0"),
            autoincrement=False,
            nullable=False,
            comment="Monitoring task hours for the month",
        ),
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "carried_hours",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0.0"),
            autoincrement=False,
            nullable=False,
            comment="Hours carried from previous month",
        ),
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "assistance_hours",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0.0"),
            autoincrement=False,
            nullable=False,
            comment="Assistance task hours for the month",
        ),
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "is_final",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
            comment="Whether this record is finalized",
        ),
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "month",
            sa.VARCHAR(length=7),
            autoincrement=False,
            nullable=False,
            comment="Month in YYYY-MM format",
        ),
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "calculation_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
            comment="When the calculation was performed",
        ),
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "remaining_hours",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0.0"),
            autoincrement=False,
            nullable=False,
            comment="Remaining hours for next month",
        ),
    )
    op.add_column(
        "attendance_records",
        sa.Column(
            "repair_task_hours",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0.0"),
            autoincrement=False,
            nullable=False,
            comment="Repair task hours for the month",
        ),
    )
    op.create_table_comment(
        "attendance_records",
        "Monthly attendance records table",
        existing_comment=None,
        schema=None,
    )
    op.drop_constraint(
        "uq_attendance_member_date", "attendance_records", type_="unique"
    )
    op.drop_index(
        op.f("ix_attendance_records_attendance_date"), table_name="attendance_records"
    )
    op.drop_index("idx_attendance_date_member", table_name="attendance_records")
    op.create_unique_constraint(
        op.f("uq_attendance_member_month"),
        "attendance_records",
        ["member_id", "month"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_attendance_month"), "attendance_records", ["month"], unique=False
    )
    op.create_index(
        op.f("idx_attendance_member_month"),
        "attendance_records",
        ["member_id", "month"],
        unique=False,
    )
    op.drop_column("attendance_records", "early_checkout_minutes")
    op.drop_column("attendance_records", "is_early_checkout")
    op.drop_column("attendance_records", "late_checkin_minutes")
    op.drop_column("attendance_records", "is_late_checkin")
    op.drop_column("attendance_records", "notes")
    op.drop_column("attendance_records", "location")
    op.drop_column("attendance_records", "status")
    op.drop_column("attendance_records", "work_hours")
    op.drop_column("attendance_records", "checkout_time")
    op.drop_column("attendance_records", "checkin_time")
    op.drop_column("attendance_records", "attendance_date")
    op.alter_column(
        "assistance_tasks",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING",
            "IN_PROGRESS",
            "COMPLETED",
            "CANCELLED",
            "ON_HOLD",
            name="taskstatus",
        ),
        server_default=sa.text("'COMPLETED'::taskstatus"),
        existing_comment="Task status",
        existing_nullable=False,
    )
    op.create_table(
        "attendance_configurations",
        sa.Column(
            "id",
            sa.INTEGER(),
            autoincrement=True,
            nullable=False,
            comment="Primary key",
        ),
        sa.Column(
            "config_key",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
            comment="Configuration key",
        ),
        sa.Column(
            "config_value",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
            comment="Configuration value",
        ),
        sa.Column(
            "description",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="Configuration description",
        ),
        sa.Column(
            "value_type",
            sa.VARCHAR(length=20),
            server_default=sa.text("'string'::character varying"),
            autoincrement=False,
            nullable=False,
            comment="Value data type (int, float, string, bool)",
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
            comment="Whether this configuration is active",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
            comment="Record creation timestamp",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
            comment="Record last update timestamp",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_configurations")),
        sa.UniqueConstraint(
            "config_key",
            name=op.f("uq_attendance_config_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        comment="Attendance calculation configurations",
    )
    op.create_index(
        op.f("ix_attendance_configurations_id"),
        "attendance_configurations",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_configurations_config_key"),
        "attendance_configurations",
        ["config_key"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_monthly_attendance_summaries_member_id"),
        table_name="monthly_attendance_summaries",
    )
    op.drop_index(
        op.f("ix_monthly_attendance_summaries_id"),
        table_name="monthly_attendance_summaries",
    )
    op.drop_index("idx_summary_year_month", table_name="monthly_attendance_summaries")
    op.drop_index("idx_summary_member_year", table_name="monthly_attendance_summaries")
    op.drop_table("monthly_attendance_summaries")
    op.drop_index(
        op.f("ix_attendance_exceptions_status"), table_name="attendance_exceptions"
    )
    op.drop_index(
        op.f("ix_attendance_exceptions_member_id"), table_name="attendance_exceptions"
    )
    op.drop_index(
        op.f("ix_attendance_exceptions_id"), table_name="attendance_exceptions"
    )
    op.drop_index(
        op.f("ix_attendance_exceptions_exception_date"),
        table_name="attendance_exceptions",
    )
    op.drop_index("idx_exception_status_date", table_name="attendance_exceptions")
    op.drop_index("idx_exception_member_date", table_name="attendance_exceptions")
    op.drop_table("attendance_exceptions")
    # ### end Alembic commands ###
