"""Add offline task marking fields to repair_tasks

Revision ID: 619f3900d258
Revises: 8f982508d35c
Create Date: 2025-09-01 00:04:21.962337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '619f3900d258'
down_revision: Union[str, None] = '8f982508d35c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair_tasks', sa.Column('is_offline_marked', sa.Boolean(), nullable=False, comment='线下单标记'))
    op.add_column('repair_tasks', sa.Column('offline_inspection_result', sa.Text(), nullable=True, comment='线下检查结果描述'))
    op.add_column('repair_tasks', sa.Column('offline_images', sa.JSON(), nullable=True, comment='线下任务相关图片路径列表'))
    op.add_column('repair_tasks', sa.Column('offline_marked_by', sa.Integer(), nullable=True, comment='线下单标记人员ID'))
    op.add_column('repair_tasks', sa.Column('offline_marked_at', sa.DateTime(timezone=True), nullable=True, comment='线下单标记时间'))
    op.create_foreign_key(None, 'repair_tasks', 'members', ['offline_marked_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repair_tasks', type_='foreignkey')
    op.drop_column('repair_tasks', 'offline_marked_at')
    op.drop_column('repair_tasks', 'offline_marked_by')
    op.drop_column('repair_tasks', 'offline_images')
    op.drop_column('repair_tasks', 'offline_inspection_result')
    op.drop_column('repair_tasks', 'is_offline_marked')
    # ### end Alembic commands ###