"""Initial migration with all tables

Revision ID: d1402934c1fc
Revises: 
Create Date: 2025-09-26 10:28:44.862685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1402934c1fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录用户名（不含特殊字符和中文，可修改）'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='真实姓名（可含中文和·符号）'),
    sa.Column('student_id', sa.String(length=20), nullable=True, comment='学号/员工号（纯数字，可选）'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='手机号（纯数字，可选）'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱地址（可选）'),
    sa.Column('department', sa.String(length=100), nullable=False, comment='部门（默认信息化建设处）'),
    sa.Column('class_name', sa.String(length=50), nullable=False, comment='班级（必填）'),
    sa.Column('group_id', sa.Integer(), nullable=True, comment='小组ID（可选）'),
    sa.Column('join_date', sa.Date(), nullable=False, comment='入职日期（默认导入时间）'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希（初始密码123456）'),
    sa.Column('role', postgresql.ENUM('admin', 'group_leader', 'member', 'guest', name='userrole'), nullable=False, comment='用户角色'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='在职状态（True=在职，False=离职）'),
    sa.Column('profile_completed', sa.Boolean(), nullable=False, comment='是否已完善个人信息（首次登录需要完善）'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='邮箱验证状态'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('login_count', sa.Integer(), nullable=False, comment='登录次数'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', name='uq_member_student_id'),
    sa.UniqueConstraint('username', name='uq_member_username'),
    comment='成员信息表（重构版）'
    )
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_index(op.f('ix_members_name'), 'members', ['name'], unique=False)
    op.create_index(op.f('ix_members_student_id'), 'members', ['student_id'], unique=True)
    op.create_index(op.f('ix_members_username'), 'members', ['username'], unique=True)
    op.create_table('system_configs',
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置键名（唯一标识）'),
    sa.Column('config_name', sa.String(length=200), nullable=False, comment='配置显示名称'),
    sa.Column('config_description', sa.Text(), nullable=True, comment='配置描述'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='配置分类（work_hours, penalties, thresholds, general等）'),
    sa.Column('config_value', sa.Text(), nullable=True, comment='配置值（字符串格式）'),
    sa.Column('default_value', sa.Text(), nullable=True, comment='默认配置值'),
    sa.Column('value_type', sa.String(length=20), nullable=False, comment='值类型（string, integer, float, boolean, json）'),
    sa.Column('min_value', sa.Float(), nullable=True, comment='最小值（数值类型有效）'),
    sa.Column('max_value', sa.Float(), nullable=True, comment='最大值（数值类型有效）'),
    sa.Column('validation_rule', sa.Text(), nullable=True, comment='验证规则（正则表达式或其他规则）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('is_system_config', sa.Boolean(), nullable=False, comment='是否为系统内置配置（不可删除）'),
    sa.Column('required_role', sa.String(length=20), nullable=False, comment='修改此配置所需的最低角色权限'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='显示顺序'),
    sa.Column('config_group', sa.String(length=100), nullable=True, comment='配置分组（用于前端分组显示）'),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='扩展数据（JSON格式）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_config_key'), 'system_configs', ['config_key'], unique=True)
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    op.create_table('task_tags',
    sa.Column('name', sa.String(length=50), nullable=False, comment='Tag name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Tag description'),
    sa.Column('work_minutes_modifier', sa.Integer(), nullable=False, comment='Work minutes modifier (+/- minutes)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the tag is active'),
    sa.Column('tag_type', postgresql.ENUM('rush_order', 'non_default_rating', 'timeout_response', 'timeout_processing', 'bad_rating', 'bonus', 'penalty', 'category', name='tasktagtype'), nullable=False, comment='Tag type for categorization and work hour calculation'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_tags_id'), 'task_tags', ['id'], unique=False)
    op.create_index(op.f('ix_task_tags_name'), 'task_tags', ['name'], unique=True)
    op.create_table('assistance_tasks',
    sa.Column('member_id', sa.Integer(), nullable=False, comment='Assisting member ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Assistance task title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Task description'),
    sa.Column('assisted_department', sa.String(length=100), nullable=True, comment='Assisted department/team'),
    sa.Column('assisted_person', sa.String(length=50), nullable=True, comment='Assisted person name'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='Task start time'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='Task end time'),
    sa.Column('work_minutes', sa.Integer(), nullable=False, comment='Assistance work minutes'),
    sa.Column('status', postgresql.ENUM('pending', 'assigned', 'in_progress', 'completed', 'cancelled', 'on_hold', name='taskstatus'), nullable=False, comment='Task status'),
    sa.Column('approved_by', sa.Integer(), nullable=True, comment='Approver member ID'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='Approval time'),
    sa.Column('review_comment', sa.Text(), nullable=True, comment='Review comment for the assistance task'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['approved_by'], ['members.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Assistance tasks table'
    )
    op.create_index('idx_assistance_task_member_time', 'assistance_tasks', ['member_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_assistance_tasks_id'), 'assistance_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_assistance_tasks_member_id'), 'assistance_tasks', ['member_id'], unique=False)
    op.create_table('attendance_exceptions',
    sa.Column('member_id', sa.Integer(), nullable=False, comment='申請成員ID'),
    sa.Column('exception_type', sa.String(length=50), nullable=False, comment='異常類型'),
    sa.Column('exception_date', sa.Date(), nullable=False, comment='異常日期'),
    sa.Column('reason', sa.Text(), nullable=False, comment='申請理由'),
    sa.Column('supporting_documents', sa.Text(), nullable=True, comment='佐證材料'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='attendanceexceptionstatus'), nullable=False, comment='審核狀態'),
    sa.Column('applied_at', sa.DateTime(), nullable=False, comment='提交時間'),
    sa.Column('reviewer_id', sa.Integer(), nullable=True, comment='審核人ID'),
    sa.Column('reviewer_comments', sa.Text(), nullable=True, comment='審核意見'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='審核時間'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exception_member_date', 'attendance_exceptions', ['member_id', 'exception_date'], unique=False)
    op.create_index('idx_exception_status_date', 'attendance_exceptions', ['status', 'applied_at'], unique=False)
    op.create_index(op.f('ix_attendance_exceptions_exception_date'), 'attendance_exceptions', ['exception_date'], unique=False)
    op.create_index(op.f('ix_attendance_exceptions_id'), 'attendance_exceptions', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_exceptions_member_id'), 'attendance_exceptions', ['member_id'], unique=False)
    op.create_index(op.f('ix_attendance_exceptions_reviewer_id'), 'attendance_exceptions', ['reviewer_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('member_id', sa.Integer(), nullable=False, comment='成員ID'),
    sa.Column('attendance_date', sa.Date(), nullable=False, comment='考勤日期'),
    sa.Column('checkin_time', sa.DateTime(), nullable=True, comment='簽到時間'),
    sa.Column('checkout_time', sa.DateTime(), nullable=True, comment='簽退時間'),
    sa.Column('work_hours', sa.Float(), nullable=True, comment='工作時長（小時）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='考勤狀態'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='考勤地點'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備註'),
    sa.Column('is_late_checkin', sa.Boolean(), nullable=False, comment='是否遲到'),
    sa.Column('late_checkin_minutes', sa.Integer(), nullable=True, comment='遲到分鐘'),
    sa.Column('is_early_checkout', sa.Boolean(), nullable=False, comment='是否早退'),
    sa.Column('early_checkout_minutes', sa.Integer(), nullable=True, comment='早退分鐘'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'attendance_date', name='uq_attendance_member_date')
    )
    op.create_index('idx_attendance_date_member', 'attendance_records', ['attendance_date', 'member_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_attendance_date'), 'attendance_records', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_records_member_id'), 'attendance_records', ['member_id'], unique=False)
    op.create_table('monitoring_tasks',
    sa.Column('member_id', sa.Integer(), nullable=False, comment='Assigned member ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Task title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Task description'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='Monitoring location'),
    sa.Column('monitoring_type', sa.String(length=50), nullable=False, comment='Monitoring type (inspection, maintenance, etc.)'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='Task start time'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='Task end time'),
    sa.Column('work_minutes', sa.Integer(), nullable=False, comment='Actual work minutes'),
    sa.Column('cabinet_count', sa.Integer(), nullable=True, comment='巡检机柜数量（用于计算工时）'),
    sa.Column('minutes_per_cabinet', sa.Integer(), nullable=False, comment='每个机柜的巡检时长（分钟）'),
    sa.Column('inspection_notes', sa.Text(), nullable=True, comment='巡检记录和备注'),
    sa.Column('equipment_checked', sa.JSON(), nullable=True, comment='已检查设备清单（JSON格式）'),
    sa.Column('issues_found', sa.JSON(), nullable=True, comment='发现的问题记录（JSON格式）'),
    sa.Column('status', postgresql.ENUM('pending', 'assigned', 'in_progress', 'completed', 'cancelled', 'on_hold', name='taskstatus'), nullable=False, comment='Task status'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Monitoring tasks table'
    )
    op.create_index('idx_monitoring_task_member_time', 'monitoring_tasks', ['member_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_monitoring_tasks_id'), 'monitoring_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_monitoring_tasks_member_id'), 'monitoring_tasks', ['member_id'], unique=False)
    op.create_table('monthly_attendance_summaries',
    sa.Column('member_id', sa.Integer(), nullable=False, comment='成員ID'),
    sa.Column('year', sa.Integer(), nullable=False, comment='年份'),
    sa.Column('month', sa.Integer(), nullable=False, comment='月份'),
    sa.Column('repair_task_hours', sa.Float(), nullable=True, comment='報修任務工時'),
    sa.Column('monitoring_hours', sa.Float(), nullable=True, comment='監控任務工時'),
    sa.Column('assistance_hours', sa.Float(), nullable=True, comment='協助任務工時'),
    sa.Column('carried_hours', sa.Float(), nullable=True, comment='上月結轉工時'),
    sa.Column('total_hours', sa.Float(), nullable=True, comment='實際總工時'),
    sa.Column('remaining_hours', sa.Float(), nullable=True, comment='可結轉剩餘工時'),
    sa.Column('online_repair_hours', sa.Float(), nullable=True, comment='線上報修工時'),
    sa.Column('offline_repair_hours', sa.Float(), nullable=True, comment='線下報修工時'),
    sa.Column('rush_task_hours', sa.Float(), nullable=True, comment='爆單任務加成'),
    sa.Column('positive_review_hours', sa.Float(), nullable=True, comment='好評獎勵工時'),
    sa.Column('penalty_hours', sa.Float(), nullable=True, comment='懲罰扣時'),
    sa.Column('late_response_penalty_hours', sa.Float(), nullable=True, comment='超時響應扣時'),
    sa.Column('late_completion_penalty_hours', sa.Float(), nullable=True, comment='超時處理扣時'),
    sa.Column('negative_review_penalty_hours', sa.Float(), nullable=True, comment='差評扣時'),
    sa.Column('total_work_days', sa.Integer(), nullable=True, comment='總工作日'),
    sa.Column('attended_days', sa.Integer(), nullable=True, comment='實際出勤日'),
    sa.Column('late_days', sa.Integer(), nullable=True, comment='遲到天數'),
    sa.Column('early_checkout_days', sa.Integer(), nullable=True, comment='早退天數'),
    sa.Column('task_completion_count', sa.Integer(), nullable=True, comment='完成任務數'),
    sa.Column('average_task_rating', sa.Float(), nullable=True, comment='平均評分'),
    sa.Column('summary_notes', sa.Text(), nullable=True, comment='匯總備註'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'year', 'month', name='uq_attendance_summary_member_month')
    )
    op.create_index('idx_summary_member_year', 'monthly_attendance_summaries', ['member_id', 'year'], unique=False)
    op.create_index('idx_summary_year_month', 'monthly_attendance_summaries', ['year', 'month'], unique=False)
    op.create_index(op.f('ix_monthly_attendance_summaries_id'), 'monthly_attendance_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_attendance_summaries_member_id'), 'monthly_attendance_summaries', ['member_id'], unique=False)
    op.create_table('repair_tasks',
    sa.Column('task_id', sa.String(length=50), nullable=False, comment='External task ID from work order system'),
    sa.Column('work_order_id', sa.String(length=50), nullable=True, comment='Work order ID from external system'),
    sa.Column('member_id', sa.Integer(), nullable=False, comment='Assigned member ID'),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True, comment='Task assignment time'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Task title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed task description'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='Task location'),
    sa.Column('category', postgresql.ENUM('network_repair', 'hardware_repair', 'software_support', 'software_issue', 'monitoring', 'assistance', 'other', name='taskcategory'), nullable=False, comment='Task category'),
    sa.Column('priority', postgresql.ENUM('low', 'medium', 'high', 'urgent', name='taskpriority'), nullable=False, comment='Task priority'),
    sa.Column('urgency_level', sa.String(length=20), nullable=False, comment='Task urgency level'),
    sa.Column('status', postgresql.ENUM('pending', 'assigned', 'in_progress', 'completed', 'cancelled', 'on_hold', name='taskstatus'), nullable=False, comment='Task status'),
    sa.Column('task_type', postgresql.ENUM('online', 'offline', 'repair', 'assistance', name='tasktype'), nullable=False, comment='Task type (online/offline)'),
    sa.Column('report_time', sa.DateTime(timezone=True), nullable=False, comment='Task report time'),
    sa.Column('response_time', sa.DateTime(timezone=True), nullable=True, comment='Task response time'),
    sa.Column('completion_time', sa.DateTime(timezone=True), nullable=True, comment='Task completion time'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True, comment='Task due date (usually equals completion_time from import data)'),
    sa.Column('feedback', sa.Text(), nullable=True, comment='User feedback'),
    sa.Column('rating', sa.Integer(), nullable=True, comment='User rating (1-5 stars)'),
    sa.Column('reporter_name', sa.String(length=50), nullable=True, comment='Reporter name'),
    sa.Column('reporter_contact', sa.String(length=100), nullable=True, comment='Reporter contact information'),
    sa.Column('reporter_phone', sa.String(length=20), nullable=True, comment='Reporter phone number'),
    sa.Column('work_minutes', sa.Integer(), nullable=False, comment='Calculated work minutes'),
    sa.Column('base_work_minutes', sa.Integer(), nullable=False, comment='Base work minutes before modifiers'),
    sa.Column('import_batch_id', sa.String(length=50), nullable=True, comment='Import batch ID for tracking'),
    sa.Column('is_matched', sa.Boolean(), nullable=False, comment='Whether task was matched during import'),
    sa.Column('original_data', sa.JSON(), nullable=True, comment='A表原始数据完整保存'),
    sa.Column('matched_member_data', sa.JSON(), nullable=True, comment='B表匹配的成员数据'),
    sa.Column('is_rush_order', sa.Boolean(), nullable=False, comment='爆单标记，独立计算工时'),
    sa.Column('work_order_status', sa.String(length=50), nullable=True, comment='A表工单状态（用于状态映射）'),
    sa.Column('repair_form', sa.String(length=50), nullable=True, comment='B表检修形式（用于线上/线下判断）'),
    sa.Column('is_offline_marked', sa.Boolean(), nullable=False, comment='线下单标记'),
    sa.Column('offline_inspection_result', sa.Text(), nullable=True, comment='线下检查结果描述'),
    sa.Column('offline_images', sa.JSON(), nullable=True, comment='线下任务相关图片路径列表'),
    sa.Column('offline_marked_by', sa.Integer(), nullable=True, comment='线下单标记人员ID'),
    sa.Column('offline_marked_at', sa.DateTime(timezone=True), nullable=True, comment='线下单标记时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['offline_marked_by'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', name='uq_repair_task_task_id'),
    comment='Repair tasks table'
    )
    op.create_index('idx_repair_task_import_batch', 'repair_tasks', ['import_batch_id'], unique=False)
    op.create_index('idx_repair_task_member_status', 'repair_tasks', ['member_id', 'status'], unique=False)
    op.create_index('idx_repair_task_report_time', 'repair_tasks', ['report_time'], unique=False)
    op.create_index(op.f('ix_repair_tasks_id'), 'repair_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_repair_tasks_member_id'), 'repair_tasks', ['member_id'], unique=False)
    op.create_index(op.f('ix_repair_tasks_report_time'), 'repair_tasks', ['report_time'], unique=False)
    op.create_index(op.f('ix_repair_tasks_status'), 'repair_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_repair_tasks_task_id'), 'repair_tasks', ['task_id'], unique=True)
    op.create_table('task_tag_associations',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['task_tags.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['repair_tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'tag_id'),
    comment='Association table for tasks and tags'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_tag_associations')
    op.drop_index(op.f('ix_repair_tasks_task_id'), table_name='repair_tasks')
    op.drop_index(op.f('ix_repair_tasks_status'), table_name='repair_tasks')
    op.drop_index(op.f('ix_repair_tasks_report_time'), table_name='repair_tasks')
    op.drop_index(op.f('ix_repair_tasks_member_id'), table_name='repair_tasks')
    op.drop_index(op.f('ix_repair_tasks_id'), table_name='repair_tasks')
    op.drop_index('idx_repair_task_report_time', table_name='repair_tasks')
    op.drop_index('idx_repair_task_member_status', table_name='repair_tasks')
    op.drop_index('idx_repair_task_import_batch', table_name='repair_tasks')
    op.drop_table('repair_tasks')
    op.drop_index(op.f('ix_monthly_attendance_summaries_member_id'), table_name='monthly_attendance_summaries')
    op.drop_index(op.f('ix_monthly_attendance_summaries_id'), table_name='monthly_attendance_summaries')
    op.drop_index('idx_summary_year_month', table_name='monthly_attendance_summaries')
    op.drop_index('idx_summary_member_year', table_name='monthly_attendance_summaries')
    op.drop_table('monthly_attendance_summaries')
    op.drop_index(op.f('ix_monitoring_tasks_member_id'), table_name='monitoring_tasks')
    op.drop_index(op.f('ix_monitoring_tasks_id'), table_name='monitoring_tasks')
    op.drop_index('idx_monitoring_task_member_time', table_name='monitoring_tasks')
    op.drop_table('monitoring_tasks')
    op.drop_index(op.f('ix_attendance_records_member_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_attendance_date'), table_name='attendance_records')
    op.drop_index('idx_attendance_date_member', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_attendance_exceptions_reviewer_id'), table_name='attendance_exceptions')
    op.drop_index(op.f('ix_attendance_exceptions_member_id'), table_name='attendance_exceptions')
    op.drop_index(op.f('ix_attendance_exceptions_id'), table_name='attendance_exceptions')
    op.drop_index(op.f('ix_attendance_exceptions_exception_date'), table_name='attendance_exceptions')
    op.drop_index('idx_exception_status_date', table_name='attendance_exceptions')
    op.drop_index('idx_exception_member_date', table_name='attendance_exceptions')
    op.drop_table('attendance_exceptions')
    op.drop_index(op.f('ix_assistance_tasks_member_id'), table_name='assistance_tasks')
    op.drop_index(op.f('ix_assistance_tasks_id'), table_name='assistance_tasks')
    op.drop_index('idx_assistance_task_member_time', table_name='assistance_tasks')
    op.drop_table('assistance_tasks')
    op.drop_index(op.f('ix_task_tags_name'), table_name='task_tags')
    op.drop_index(op.f('ix_task_tags_id'), table_name='task_tags')
    op.drop_table('task_tags')
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_config_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_members_username'), table_name='members')
    op.drop_index(op.f('ix_members_student_id'), table_name='members')
    op.drop_index(op.f('ix_members_name'), table_name='members')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###