"""Add inspection fields to monitoring tasks

Revision ID: 77468d69bee0
Revises: 619f3900d258
Create Date: 2025-09-01 00:28:11.062936

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77468d69bee0"
down_revision: Union[str, None] = "619f3900d258"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monitoring_tasks",
        sa.Column(
            "cabinet_count",
            sa.Integer(),
            nullable=True,
            comment="巡检机柜数量（用于计算工时）",
        ),
    )
    op.add_column(
        "monitoring_tasks",
        sa.Column(
            "minutes_per_cabinet",
            sa.Integer(),
            nullable=False,
            comment="每个机柜的巡检时长（分钟）",
        ),
    )
    op.add_column(
        "monitoring_tasks",
        sa.Column(
            "inspection_notes", sa.Text(), nullable=True, comment="巡检记录和备注"
        ),
    )
    op.add_column(
        "monitoring_tasks",
        sa.Column(
            "equipment_checked",
            sa.JSON(),
            nullable=True,
            comment="已检查设备清单（JSON格式）",
        ),
    )
    op.add_column(
        "monitoring_tasks",
        sa.Column(
            "issues_found",
            sa.JSON(),
            nullable=True,
            comment="发现的问题记录（JSON格式）",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("monitoring_tasks", "issues_found")
    op.drop_column("monitoring_tasks", "equipment_checked")
    op.drop_column("monitoring_tasks", "inspection_notes")
    op.drop_column("monitoring_tasks", "minutes_per_cabinet")
    op.drop_column("monitoring_tasks", "cabinet_count")
    # ### end Alembic commands ###
