"""Fix database schema to match current models

Revision ID: 36714b7138b8
Revises: 20250809_1110
Create Date: 2025-08-18 13:08:40.414393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36714b7138b8'
down_revision: Union[str, None] = '20250809_1110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create missing enum types first (PostgreSQL doesn't support IF NOT EXISTS for CREATE TYPE)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE tasktagtype AS ENUM ('rush_order', 'non_default_rating', 'timeout_response', 'timeout_processing', 'bad_rating', 'bonus', 'penalty', 'category');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    # 安全创建 assistance_tasks 表的外键约束，仅在表存在时执行
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'assistance_tasks') THEN
                -- 检查外键约束是否已存在，避免重复创建
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.table_constraints 
                    WHERE table_name = 'assistance_tasks' 
                    AND constraint_type = 'FOREIGN KEY'
                    AND constraint_name LIKE '%member_id%'
                ) THEN
                    ALTER TABLE assistance_tasks ADD CONSTRAINT fk_assistance_tasks_member_id 
                    FOREIGN KEY (member_id) REFERENCES members(id);
                END IF;
            END IF;
        END $$;
    """)
    op.create_foreign_key(None, 'attendance_exceptions', 'members', ['reviewer_id'], ['id'])
    op.create_foreign_key(None, 'attendance_exceptions', 'members', ['member_id'], ['id'])
    op.create_foreign_key(None, 'attendance_records', 'members', ['member_id'], ['id'])
    op.add_column('members', sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱地址（可选）'))
    op.add_column('members', sa.Column('group_id', sa.Integer(), nullable=True, comment='小组ID（可选）'))
    op.alter_column('members', 'student_id',
               existing_type=sa.VARCHAR(length=20),
               comment='学号/员工号（纯数字，可选）',
               existing_comment='学号/员工号（纯数字，必填）',
               existing_nullable=True)
    op.alter_column('members', 'profile_completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='是否已完善个人信息（首次登录需要完善）',
               existing_nullable=False)
    op.alter_column('members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation timestamp',
               existing_comment='记录创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record last update timestamp',
               existing_comment='记录更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_members_student_id'), table_name='members')
    op.create_index(op.f('ix_members_student_id'), 'members', ['student_id'], unique=True)
    op.drop_index(op.f('ix_members_username'), table_name='members')
    op.create_index(op.f('ix_members_username'), 'members', ['username'], unique=True)
    # 安全创建 monitoring_tasks 表的外键约束，仅在表存在时执行
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'monitoring_tasks') THEN
                -- 检查外键约束是否已存在，避免重复创建
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.table_constraints 
                    WHERE table_name = 'monitoring_tasks' 
                    AND constraint_type = 'FOREIGN KEY'
                    AND constraint_name LIKE '%member_id%'
                ) THEN
                    ALTER TABLE monitoring_tasks ADD CONSTRAINT fk_monitoring_tasks_member_id 
                    FOREIGN KEY (member_id) REFERENCES members(id);
                END IF;
            END IF;
        END $$;
    """)
    op.add_column('monthly_attendance_summaries', sa.Column('monitoring_hours', sa.Float(), nullable=True, comment='本月监控任务累计时长（小时）'))
    op.add_column('monthly_attendance_summaries', sa.Column('assistance_hours', sa.Float(), nullable=True, comment='本月协助任务累计时长（小时）'))
    op.add_column('monthly_attendance_summaries', sa.Column('carried_hours', sa.Float(), nullable=True, comment='上月结转的剩余时长（小时）'))
    op.add_column('monthly_attendance_summaries', sa.Column('total_hours', sa.Float(), nullable=True, comment='实际总工时（小时）'))
    op.add_column('monthly_attendance_summaries', sa.Column('remaining_hours', sa.Float(), nullable=True, comment='扣除后可结转至下月的剩余工时'))
    op.add_column('monthly_attendance_summaries', sa.Column('online_repair_hours', sa.Float(), nullable=True, comment='线上报修任务时长（40分钟/单）'))
    op.add_column('monthly_attendance_summaries', sa.Column('offline_repair_hours', sa.Float(), nullable=True, comment='线下报修任务时长（100分钟/单）'))
    op.add_column('monthly_attendance_summaries', sa.Column('rush_task_hours', sa.Float(), nullable=True, comment='爆单任务额外时长（15分钟/单）'))
    op.add_column('monthly_attendance_summaries', sa.Column('positive_review_hours', sa.Float(), nullable=True, comment='非默认好评额外时长（30分钟/单）'))
    op.add_column('monthly_attendance_summaries', sa.Column('late_response_penalty_hours', sa.Float(), nullable=True, comment='超时响应扣时（30分钟/单/人）'))
    op.add_column('monthly_attendance_summaries', sa.Column('late_completion_penalty_hours', sa.Float(), nullable=True, comment='超时处理扣时（30分钟/人）'))
    op.add_column('monthly_attendance_summaries', sa.Column('negative_review_penalty_hours', sa.Float(), nullable=True, comment='差评扣时（60分钟/单/人）'))
    op.alter_column('monthly_attendance_summaries', 'repair_task_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='本月报修任务累计时长（小时）',
               existing_comment='Hours from repair tasks',
               existing_nullable=True)
    op.alter_column('monthly_attendance_summaries', 'penalty_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='异常扣时总计（小时）',
               existing_comment='Penalty hours (late response, negative reviews)',
               existing_nullable=True)
    op.create_foreign_key(None, 'monthly_attendance_summaries', 'members', ['member_id'], ['id'])
    op.drop_column('monthly_attendance_summaries', 'assistance_task_hours')
    op.drop_column('monthly_attendance_summaries', 'overtime_hours')
    op.drop_column('monthly_attendance_summaries', 'total_work_hours')
    op.drop_column('monthly_attendance_summaries', 'bonus_hours')
    op.drop_column('monthly_attendance_summaries', 'monitoring_task_hours')
    op.drop_column('monthly_attendance_summaries', 'total_attendance_hours')
    # 安全修改 repair_tasks 表，仅在表存在时执行
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'repair_tasks') THEN
                -- 修改 is_rush_order 列的默认值
                ALTER TABLE repair_tasks ALTER COLUMN is_rush_order DROP DEFAULT;
                
                -- 删除索引（如果存在）
                DROP INDEX IF EXISTS idx_repair_tasks_is_rush_order;
                DROP INDEX IF EXISTS idx_repair_tasks_work_order_status;
                
                -- 检查并创建外键约束
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.table_constraints 
                    WHERE table_name = 'repair_tasks' 
                    AND constraint_type = 'FOREIGN KEY'
                    AND constraint_name LIKE '%member_id%'
                ) THEN
                    ALTER TABLE repair_tasks ADD CONSTRAINT fk_repair_tasks_member_id 
                    FOREIGN KEY (member_id) REFERENCES members(id);
                END IF;
            END IF;
        END $$;
    """)
    # Convert existing task_tags.tag_type from VARCHAR to enum with USING clause
    op.execute("""
        ALTER TABLE task_tags 
        ALTER COLUMN tag_type TYPE tasktagtype 
        USING (CASE 
            WHEN tag_type = 'category' THEN 'category'::tasktagtype
            WHEN tag_type = 'bonus' THEN 'bonus'::tasktagtype
            WHEN tag_type = 'penalty' THEN 'penalty'::tasktagtype
            WHEN tag_type = 'rush_order' THEN 'rush_order'::tasktagtype
            WHEN tag_type = 'non_default_rating' THEN 'non_default_rating'::tasktagtype
            WHEN tag_type = 'timeout_response' THEN 'timeout_response'::tasktagtype
            WHEN tag_type = 'timeout_processing' THEN 'timeout_processing'::tasktagtype
            WHEN tag_type = 'bad_rating' THEN 'bad_rating'::tasktagtype
            ELSE 'category'::tasktagtype
        END)
    """)
    
    # Make column NOT NULL and update comment
    op.alter_column('task_tags', 'tag_type',
               existing_type=sa.Enum('rush_order', 'non_default_rating', 'timeout_response', 'timeout_processing', 'bad_rating', 'bonus', 'penalty', 'category', name='tasktagtype'),
               nullable=False,
               comment='Tag type for categorization and work hour calculation',
               existing_comment='Tag type (bonus, penalty, category)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_tags', 'tag_type',
               existing_type=sa.Enum('RUSH_ORDER', 'NON_DEFAULT_RATING', 'TIMEOUT_RESPONSE', 'TIMEOUT_PROCESSING', 'BAD_RATING', 'BONUS', 'PENALTY', 'CATEGORY', name='tasktagtype'),
               type_=sa.VARCHAR(length=30),
               nullable=True,
               comment='Tag type (bonus, penalty, category)',
               existing_comment='Tag type for categorization and work hour calculation')
    # 安全恢复 repair_tasks 表，仅在表存在时执行
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'repair_tasks') THEN
                -- 删除外键约束
                IF EXISTS (
                    SELECT 1 FROM information_schema.table_constraints 
                    WHERE table_name = 'repair_tasks' 
                    AND constraint_type = 'FOREIGN KEY'
                    AND constraint_name = 'fk_repair_tasks_member_id'
                ) THEN
                    ALTER TABLE repair_tasks DROP CONSTRAINT fk_repair_tasks_member_id;
                END IF;
                
                -- 重新创建索引
                CREATE INDEX IF NOT EXISTS idx_repair_tasks_work_order_status ON repair_tasks(work_order_status);
                CREATE INDEX IF NOT EXISTS idx_repair_tasks_is_rush_order ON repair_tasks(is_rush_order);
                
                -- 恢复 is_rush_order 列的默认值
                ALTER TABLE repair_tasks ALTER COLUMN is_rush_order SET DEFAULT false;
            END IF;
        END $$;
    """)
    op.add_column('monthly_attendance_summaries', sa.Column('total_attendance_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Total hours from attendance records'))
    op.add_column('monthly_attendance_summaries', sa.Column('monitoring_task_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Hours from monitoring tasks'))
    op.add_column('monthly_attendance_summaries', sa.Column('bonus_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Bonus hours (rush tasks, positive reviews)'))
    op.add_column('monthly_attendance_summaries', sa.Column('total_work_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Total calculated work hours'))
    op.add_column('monthly_attendance_summaries', sa.Column('overtime_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Overtime hours'))
    op.add_column('monthly_attendance_summaries', sa.Column('assistance_task_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Hours from assistance tasks'))
    op.drop_constraint(None, 'monthly_attendance_summaries', type_='foreignkey')
    op.alter_column('monthly_attendance_summaries', 'penalty_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Penalty hours (late response, negative reviews)',
               existing_comment='异常扣时总计（小时）',
               existing_nullable=True)
    op.alter_column('monthly_attendance_summaries', 'repair_task_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Hours from repair tasks',
               existing_comment='本月报修任务累计时长（小时）',
               existing_nullable=True)
    op.drop_column('monthly_attendance_summaries', 'negative_review_penalty_hours')
    op.drop_column('monthly_attendance_summaries', 'late_completion_penalty_hours')
    op.drop_column('monthly_attendance_summaries', 'late_response_penalty_hours')
    op.drop_column('monthly_attendance_summaries', 'positive_review_hours')
    op.drop_column('monthly_attendance_summaries', 'rush_task_hours')
    op.drop_column('monthly_attendance_summaries', 'offline_repair_hours')
    op.drop_column('monthly_attendance_summaries', 'online_repair_hours')
    op.drop_column('monthly_attendance_summaries', 'remaining_hours')
    op.drop_column('monthly_attendance_summaries', 'total_hours')
    op.drop_column('monthly_attendance_summaries', 'carried_hours')
    op.drop_column('monthly_attendance_summaries', 'assistance_hours')
    op.drop_column('monthly_attendance_summaries', 'monitoring_hours')
    # 安全删除 monitoring_tasks 表的外键约束，仅在表存在时执行
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'monitoring_tasks') THEN
                -- 删除外键约束
                IF EXISTS (
                    SELECT 1 FROM information_schema.table_constraints 
                    WHERE table_name = 'monitoring_tasks' 
                    AND constraint_type = 'FOREIGN KEY'
                    AND constraint_name = 'fk_monitoring_tasks_member_id'
                ) THEN
                    ALTER TABLE monitoring_tasks DROP CONSTRAINT fk_monitoring_tasks_member_id;
                END IF;
            END IF;
        END $$;
    """)
    op.drop_index(op.f('ix_members_username'), table_name='members')
    op.create_index(op.f('ix_members_username'), 'members', ['username'], unique=False)
    op.drop_index(op.f('ix_members_student_id'), table_name='members')
    op.create_index(op.f('ix_members_student_id'), 'members', ['student_id'], unique=False)
    op.alter_column('members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录更新时间',
               existing_comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间',
               existing_comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('members', 'profile_completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='是否已完善个人信息（首次登录需要完善）',
               existing_nullable=False)
    op.alter_column('members', 'student_id',
               existing_type=sa.VARCHAR(length=20),
               comment='学号/员工号（纯数字，必填）',
               existing_comment='学号/员工号（纯数字，可选）',
               existing_nullable=True)
    op.drop_column('members', 'group_id')
    op.drop_column('members', 'email')
    op.drop_constraint(None, 'attendance_records', type_='foreignkey')
    op.drop_constraint(None, 'attendance_exceptions', type_='foreignkey')
    op.drop_constraint(None, 'attendance_exceptions', type_='foreignkey')
    # 安全删除 assistance_tasks 表的外键约束，仅在表存在时执行
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'assistance_tasks') THEN
                -- 删除外键约束
                IF EXISTS (
                    SELECT 1 FROM information_schema.table_constraints 
                    WHERE table_name = 'assistance_tasks' 
                    AND constraint_type = 'FOREIGN KEY'
                    AND constraint_name = 'fk_assistance_tasks_member_id'
                ) THEN
                    ALTER TABLE assistance_tasks DROP CONSTRAINT fk_assistance_tasks_member_id;
                END IF;
            END IF;
        END $$;
    """)
    
    # Drop the enum type created in upgrade
    op.execute("DROP TYPE IF EXISTS tasktagtype CASCADE")
    # ### end Alembic commands ###