"""Add assistance task approval fields

Revision ID: 8f982508d35c
Revises: 8e5236d2ab84
Create Date: 2025-09-01 00:01:40.942714

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f982508d35c"
down_revision: Union[str, None] = "8e5236d2ab84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistance_tasks",
        sa.Column(
            "approved_by", sa.Integer(), nullable=True, comment="Approver member ID"
        ),
    )
    op.add_column(
        "assistance_tasks",
        sa.Column(
            "approved_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Approval time",
        ),
    )
    op.create_foreign_key(None, "assistance_tasks", "members", ["approved_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "assistance_tasks", type_="foreignkey")
    op.drop_column("assistance_tasks", "approved_at")
    op.drop_column("assistance_tasks", "approved_by")
    # ### end Alembic commands ###
